### ISSUE TITLE
ScriptError: Authorization is required to perform that action.

### ISSUE THREAD

**Issue by GauBen** [zsucic/captionmaker#1]
Hello, I can't make caption maker work, I have the following error:

<img width="224" alt="image" src="https://user-images.githubusercontent.com/48261497/185140609-cd41548a-80e1-4158-b3c7-ff63dc13faa6.png">

Thanks in advance for your help

**Comment by zsucic** [comment]
You have to use the same account in google docs that you used to install
caption maker. If you're using 2 or more google accounts in the same
browser the authentication is messed up. I'd suggest setting up a separate
browser profile for each account.
See https://support.google.com/a/users/answer/9310144?hl=en

**Comment by GauBen** [comment]
Thanks for the quick answer!
