### ISSUE TITLE
ScriptError: Authorization is required to perform that action.

### ISSUE THREAD

**Issue by tclewis29** [zsucic/captionmaker#3]
Hi, 

I have followed the setup instructions but am getting this message:

```ScriptError: Authorization is required to perform that action.```

How can I solve this?

Many thanks

**Comment by zsucic** [comment]
Try using the same google account for both the installation of caption
maker and accessing the document. The error you're getting is usually when
there were two different accounts used for installation and then for
document it self.
If not that, check that the account you're using on the document actually
has privileges to edit the document

**Comment by tclewis29** [comment]
Great thank you
