### ISSUE TITLE
Page numbers in list of images and tables

### ISSUE THREAD

**Issue by tclewis29** [zsucic/captionmaker#4]
Hi, Is there any way to get page numbers in the list of image and/or tables? I can't seem to find an option, would be great as if there is this functionality.

**Comment by zsucic** [comment]
I'm afraid page numbers aren't possible. The google doc is not like a regular document where you have a bunch of text etc, but more like a webpage consisting of a multitude of different web elements so I believe google shows the page numbers only when actually rendering the document. In other words, the page number information isn't stored anywhere so i can't pick it up and display it...
