### ISSUE TITLE
Keeping caption with image

### ISSUE THREAD

**Issue by kaimikael** [zsucic/captionmaker#6]
Maybe this is not even doable in Google Docs, but it would be nice if one could be guaranteed that a figure and its caption are never split over a page break.  The attached screen shot shows the problem.
<img width="817" alt="Screenshot 2023-03-01 at 11 48 35" src="https://user-images.githubusercontent.com/10616212/222118259-07fa5f46-f858-4b0f-9f28-12abc068f8ef.png">

**Comment by zsucic** [comment]
Yeah, nice idea but unfortunately there is no mechanism in google docs that would enable that kind of tracking of what goes on what page. There isn't even one to find out on which page an image is... I believe that rendering the document is handled later in the process and it's only then that google docs figures out pages etc... From plugins perspective it's all just one big page ...
