### ISSUE TITLE
RFE: apply "keep with next" spacing option to prevent captions splitting across page breaks

### ISSUE THREAD

**Issue by rblue2** [zsucic/captionmaker#8]
Docs provides a 'Keep with next' spacing option. Applying this spacing option to a figure appears to prevent the caption below from getting orphaned across a page break. It would be very convenient if the CaptionMaker extension applied this automatically.

**Comment by zsucic** [comment]
Unfortunatelly, it doesn't seem that this option is available for google docs addons. These are all of the attributes that can be applied on a paragraph: https://developers.google.com/apps-script/reference/document/attribute
and none of them seem to correspond to "keep with next" or anything similar.
I've even tried getting attributes from a paragraph that was manually set as "keep with next" hoping that it was just not documented but I got this:
(in case you want to test it your self, this is the apps script code I used)
 
```
function test() {
  
      var document = DocumentApp.openById("1e2J9xWv0TDqnsl8mHn8e1zRR0yoskEE0qRYdPvdor2I");
      var body=document.getBody();
      //var paragraph=body.appendParagraph("This is a typical paragraph.");
      var num=body.getNumChildren();
      for (var i=0; i<num;i++)
      {
        var paragraph=body.getChild(i);
        var attributes=paragraph.getAttributes();
        console.log(attributes);
      }

 
}
```
 

Result:

> 11:38:11 AM	Info	{ FONT_SIZE: null,
>   SPACING_AFTER: 0,
>   HORIZONTAL_ALIGNMENT: 
>    { toString: [Function: toString],
>      name: [Function: toString],
>      toJSON: [Function: toString],
>      ordinal: [Function: ordinal],
>      compareTo: [Function: compareTo],
>      LEFT: [Circular],
>      CENTER: 
>       { toString: [Function: toString],
>         name: [Function: toString],
>         toJSON: [Function: toString],
>         ordinal: [Function: ordinal],
>         compareTo: [Function: compareTo],
>         LEFT: [Circular],
>         CENTER: [Circular],
>         RIGHT: [Object],
>         JUSTIFY: [Object] },
>      RIGHT: 
>       { toString: [Function: toString],
>         name: [Function: toString],
>         toJSON: [Function: toString],
>         ordinal: [Function: ordinal],
>         compareTo: [Function: compareTo],
>         LEFT: [Circular],
>         CENTER: [Object],
>         RIGHT: [Circular],
>         JUSTIFY: [Object] },
>      JUSTIFY: 
>       { toString: [Function: toString],
>         name: [Function: toString],
>         toJSON: [Function: toString],
>         ordinal: [Function: ordinal],
>         compareTo: [Function: compareTo],
>         LEFT: [Circular],
>         CENTER: [Object],
>         RIGHT: [Object],
>         JUSTIFY: [Circular] } },
>   LINK_URL: null,
>   INDENT_END: 0,
>   LINE_SPACING: 1.15,
>   SPACING_BEFORE: 0,
>   HEADING: 
>    { toString: [Function: toString],
>      name: [Function: toString],
>      toJSON: [Function: toString],
>      ordinal: [Function: ordinal],
>      compareTo: [Function: compareTo],
>      NORMAL: [Circular],
>      HEADING1: 
>       { toString: [Function: toString],
>         name: [Function: toString],
>         toJSON: [Function: toString],
>         ordinal: [Function: ordinal],
>         compareTo: [Function: compareTo],
>         NORMAL: [Circular],
>         HEADING1: [Circular],
>         HEADING2: [Object],
>         HEADING3: [Object],
>         HEADING4: [Object],
>         HEADING5: [Object],
>         HEADING6: [Object],
>         TITLE: [Object],
>         SUBTITLE: [Object] },
>      HEADING2: 
>       { toString: [Function: toString],
>         name: [Function: toString],
>         toJSON: [Function: toString],
>         ordinal: [Function: ordinal],
>         compareTo: [Function: compareTo],
>         NORMAL: [Circular],
>         HEADING1: [Object],
>         HEADING2: [Circular],
>         HEADING3: [Object],
>         HEADING4: [Object],
>         HEADING5: [Object],
>         HEADING6: [Object],
>         TITLE: [Object],
>         SUBTITLE: [Object] },
>      HEADING3: 
>       { toString: [Function: toString],
>         name: [Function: toString],
>         toJSON: [Function: toString],
>         ordinal: [Function: ordinal],
>         compareTo: [Function: compareTo],
>         NORMAL: [Circular],
>         HEADING1: [Object],
>         HEADING2: [Object],
>         HEADING3: [Circular],
>         HEADING4: [Object],
>         HEADING5: [Object],
>         HEADING6: [Object],
>         TITLE: [Object],
>         SUBTITLE: [Object] },
>      HEADING4: 
>       { toString: [Function: toString],
>         name: [Function: toString],
>         toJSON: [Function: toString],
>         ordinal: [Function: ordinal],
>         compareTo: [Function: compareTo],
>         NORMAL: [Circular],
>         HEADING1: [Object],
>         HEADING2: [Object],
>         HEADING3: [Object],
>         HEADING4: [Circular],
>         HEADING5: [Object],
>         HEADING6: [Object],
>         TITLE: [Object],
>         SUBTITLE: [Object] },
>      HEADING5: 
>       { toString: [Function: toString],
>         name: [Function: toString],
>         toJSON: [Function: toString],
>         ordinal: [Function: ordinal],
>         compareTo: [Function: compareTo],
>         NORMAL: [Circular],
>         HEADING1: [Object],
>         HEADING2: [Object],
>         HEADING3: [Object],
>         HEADING4: [Object],
>         HEADING5: [Circular],
>         HEADING6: [Object],
>         TITLE: [Object],
>         SUBTITLE: [Object] },
>      HEADING6: 
>       { toString: [Function: toString],
>         name: [Function: toString],
>         toJSON: [Function: toString],
>         ordinal: [Function: ordinal],
>         compareTo: [Function: compareTo],
>         NORMAL: [Circular],
>         HEADING1: [Object],
>         HEADING2: [Object],
>         HEADING3: [Object],
>         HEADING4: [Object],
>         HEADING5: [Object],
>         HEADING6: [Circular],
>         TITLE: [Object],
>         SUBTITLE: [Object] },
>      TITLE: 
>       { toString: [Function: toString],
>         name: [Function: toString],
>         toJSON: [Function: toString],
>         ordinal: [Function: ordinal],
>         compareTo: [Function: compareTo],
>         NORMAL: [Circular],
>         HEADING1: [Object],
>         HEADING2: [Object],
>         HEADING3: [Object],
>         HEADING4: [Object],
>         HEADING5: [Object],
>         HEADING6: [Object],
>         TITLE: [Circular],
>         SUBTITLE: [Object] },
>      SUBTITLE: 
>       { toString: [Function: toString],
>         name: [Function: toString],
>         toJSON: [Function: toString],
>         ordinal: [Function: ordinal],
>         compareTo: [Function: compareTo],
>         NORMAL: [Circular],
>         HEADING1: [Object],
>         HEADING2: [Object],
>         HEADING3: [Object],
>         HEADING4: [Object],
>         HEADING5: [Object],
>         HEADING6: [Object],
>         TITLE: [Object],
>         SUBTITLE: [Circular] } },
>   STRIKETHROUGH: null,
>   BOLD: null,
>   FOREGROUND_COLOR: null,
>   FONT_FAMILY: null,
>   LEFT_TO_RIGHT: true,
>   ITALIC: null,
>   INDENT_FIRST_LINE: 0,
>   INDENT_START: 0,
>   BACKGROUND_COLOR: null,
>   UNDERLINE: null }

**Comment by rblue2** [comment]
Ah, too bad. thanks for taking a look.
